// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/crm/Analytics.tsx": () => import("../components/mockups/crm/Analytics.tsx"),
  "./components/mockups/crm/CRMApp.tsx": () => import("../components/mockups/crm/CRMApp.tsx"),
  "./components/mockups/crm/Client360.tsx": () => import("../components/mockups/crm/Client360.tsx"),
  "./components/mockups/crm/CustomerService.tsx": () => import("../components/mockups/crm/CustomerService.tsx"),
  "./components/mockups/crm/Dashboard.tsx": () => import("../components/mockups/crm/Dashboard.tsx"),
  "./components/mockups/crm/IBDealRoom.tsx": () => import("../components/mockups/crm/IBDealRoom.tsx"),
  "./components/mockups/crm/LeadManagement.tsx": () => import("../components/mockups/crm/LeadManagement.tsx")
};
